repos:
-   repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        args: [--line-length=88]
      
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check
        language: system
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]
            
      - id: pytest
        name: Run pytest
        entry: poetry run pytest -s -vvv --cov=src --cov-report term-missing
        language: system
        pass_filenames: false