services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: collegium-server
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
    command: poetry run uvicorn src.server.server:app --host 0.0.0.0 --port 8000 --reload

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: collegium-client
    depends_on:
      - server
    restart: unless-stopped

  frontend: # New Angular frontend service
    build:
      context: ./angular-frontend/angular-command-centre # Path to Angular app
      dockerfile: Dockerfile
    container_name: angular-command-centre-frontend
    ports:
      - "4200:80" # Exposing Angular app on host port 4200, container runs on 80
    depends_on:
      - server # Depends on the backend server
    restart: unless-stopped
